### ISSUE TITLE
Failing DSC does not fail vagrant build

### ISSUE THREAD

**Issue by matt-richardson** [mefellows/vagrant-dsc#46]
I've been finding that if there is an issue with the DSC, it doesn't fail the vagrant build - it just continues onto the next provisioner.

[The code](https://github.com/mefellows/vagrant-dsc/blob/master/lib/vagrant-dsc/provisioner.rb#L132)
```
        if (get_configuration_status == "Failure")
          @machine.ui.error(I18n.t("failure_status"))
          show_dsc_failure_message
        end
```
appears to show an error message, but doesn't actually fail the vagrant build.

I suspect it needs to throw an exception here as well.

**Comment by matt-richardson** [comment]
Let me know if you need a repro.

**Comment by mefellows** [comment]
Thanks @matt-richardson, hmmm this might be intentional behaviour. From memory, I took inspiration from the Puppet [provisioner](https://github.com/mitchellh/vagrant/blob/9c299a2a357fcf87f356bb9d56e18a037a53d138/plugins/provisioners/puppet/config/puppet.rb) which I believe doesn't fail the build. 

It should be fairly easy to adjust, or even add a flag to adjust the behaviour. Would you be interesting in submitting a PR?

**Comment by matt-richardson** [comment]
I'll give it a go... My ruby is very rusty at the moment though...
